### PR TITLE
Fix CSVParser issues

### LINKED ISSUE #287: Ignore the last newline in CSVParser
For files that end with a newline, CSVParser::GetNextRow returns an extraneous empty line, which is not desirable

### LINKED ISSUE #288: CSVParser: "" is parsed incorrectly
`""` in a field should be parsed as `"`, but instead disappears.

### PR DESCRIPTION
**Pull request by MichaelS239**
- Add the last newline ignoring (closes #287)
- Fix CSVParser::Reset()
- Fix double quote parsing (closes #288)
- Add tests for CSVParser methods

### CODE REVIEW

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 1]
```diff
@@ -110,12 +123,26 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
 }
 
 std::vector<std::string> CSVParser::ParseString(std::string const& s) const {
+    std::string t;
+    for (size_t index = 0; index < s.size(); index++) {
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:127]:
```suggestion
    for (std::size_t index = 0; index < s.size(); index++) {
```
nit: `std::size_t` is preferred, since `size_t` is not guaranteed to be defined by the standard

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 2]
```diff
@@ -110,12 +123,26 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
...
+        if (s[index] == '\"' && index < s.size() - 1 && s[index + 1] == '\"' &&
+            (!t.size() || t[t.size() - 1] != '\\')) {
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:129]: Save `s.size()` to a variable

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 3]
```diff
@@ -110,12 +123,26 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
 }
 
 std::vector<std::string> CSVParser::ParseString(std::string const& s) const {
+    std::string t;
+    for (size_t index = 0; index < s.size(); index++) {
+        if (s[index] == '\"' && index < s.size() - 1 && s[index + 1] == '\"' &&
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:128]: nit:
```suggestion
        if (s[index] == '"' && index < s.size() - 1 && s[index + 1] == '"' &&
```

File: src/core/parser/csv_parser/csv_parser.cpp (hunk 2 above)
Comment (BUYT-1) [reply src/core/parser/csv_parser/csv_parser.cpp:129]: `\` should be escaped too

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 4]
```diff
@@ -110,12 +123,26 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
...
+
     std::vector<std::string> tokens;
     boost::escaped_list_separator<char> list_sep(escape_symbol_, separator_, quote_);
-    boost::tokenizer<boost::escaped_list_separator<char>> tokenizer(s, list_sep);
+    boost::tokenizer<boost::escaped_list_separator<char>> tokenizer(t, list_sep);
 
     for (auto& token : tokenizer) {
-        tokens.push_back(token);
+        if (token == "\"" && single_quote_is_empty_line) {
+            tokens.push_back("");
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:142]:
```suggestion
            tokens.emplace_back();
```
This doesn't create and move a `std::string`

**Review by BUYT-1 — CHANGES_REQUESTED** [review]

File: src/core/parser/csv_parser/csv_parser.cpp (hunk 2 above)
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:129]: What is this check needed for?

File: src/core/parser/csv_parser/csv_parser.cpp (hunk 1 above)
Comment (BUYT-1) [reply src/core/parser/csv_parser/csv_parser.cpp:127]: nit: add `#include <cstddef>`

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 5]
```diff
@@ -110,12 +129,30 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
...
+
     std::vector<std::string> tokens;
     boost::escaped_list_separator<char> list_sep(escape_symbol_, separator_, quote_);
-    boost::tokenizer<boost::escaped_list_separator<char>> tokenizer(s, list_sep);
+    boost::tokenizer<boost::escaped_list_separator<char>> tokenizer(t, list_sep);
 
     for (auto& token : tokenizer) {
-        tokens.push_back(token);
+        if (token == "\"" && single_quote_is_empty_line) {
+            tokens.emplace_back("");
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:152]:
```suggestion
            tokens.emplace_back();
```

File: src/core/parser/csv_parser/csv_parser.h [hunk 6]
```diff
@@ -20,6 +20,8 @@ class CSVParser : public model::IDatasetStream {
     char quote_ = '\"';
     bool has_header_;
     bool has_next_;
+    bool single_quote_is_empty_line =
+            false;  // states whether we should treat " in a field as an empty line
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.h:24]: Maybe this should always be true

**Review by BUYT-1 — CHANGES_REQUESTED** [review]

File: src/tests/test_csv_parser.cpp [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+    for (size_t index = 0; index < num_rows; index++) {
+        row = parser->GetNextRow();
+        actual.push_back(row);
+    }
+
+    ASSERT_THAT(actual, ContainerEq(expected)) << "Fail on " << path.c_str();
+}
+
+TEST(TestCSVParser, TestGetNextRow) {
+    CheckGetNextRow(test_data_dir / "NullEmpty.csv", ',', true, 4,
```
Comment (vs9h) [inline src/tests/test_csv_parser.cpp:29]: it's better to use `TableConfig` from `all_tables_config.h`.
Add new tables if necessary.

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 8]
```diff
@@ -110,12 +129,42 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
 }
 
 std::vector<std::string> CSVParser::ParseString(std::string const& s) const {
+    std::size_t const length = s.size();
+    std::string t;
+    for (std::size_t index = 0; index < length; ++index) {
+        if (s[index] == '\\') {  // preserve \ through boost parsing
+            t.append(2, '\\');
+        } else if (s[index] == '"') {  // preserve " through boost parsing
+            t.append("\\\"\"");
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:138]: And now quotes are useless, and we may as well use `boost::char_separator` instead of `boost::escaped_list_separator`.
`a,"a,a","a"` should be `a` `"a,a"` `a` but will be parsed as `a` `"a` `a"` `a`
I don't know. Maybe this is ok for now, but using a separate library for CSV parsing seems like the simplest option.

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 9]
```diff
@@ -110,12 +129,42 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
...
+    }
+
     std::vector<std::string> tokens;
     boost::escaped_list_separator<char> list_sep(escape_symbol_, separator_, quote_);
-    boost::tokenizer<boost::escaped_list_separator<char>> tokenizer(s, list_sep);
+    boost::tokenizer<boost::escaped_list_separator<char>> tokenizer(t, list_sep);
 
     for (auto& token : tokenizer) {
-        tokens.push_back(token);
+        size_t token_length = token.size();
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:149]: nit:
```suggestion
        std::size_t const token_length = token.size();
```

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 10]
```diff
@@ -110,12 +129,42 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
...
+        bool is_enclosed =
+                token_length >= 2 && token[0] == '"' &&
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:151]:
```suggestion
                token_length >= 2 && token.front() == '"' &&
```

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 11]
```diff
@@ -110,12 +129,42 @@ std::string CSVParser::GetUnparsedLine(unsigned long long const line_index) {
...
+                    token[index + 1] == '"') {  // transfer "" to " if the current field is enclosed
+                                                // in double-quotes
+                    new_token.push_back(token[index]);
+                    ++index;
+                }
+            } else {
+                new_token.push_back(token[index]);
+            }
+        }
+        tokens.emplace_back(new_token);
```
Comment (BUYT-1) [inline src/core/parser/csv_parser/csv_parser.cpp:167]:
```suggestion
        tokens.emplace_back(std::move(new_token));
```

**Review by BUYT-1 — CHANGES_REQUESTED** [review]

**Review by BUYT-1 — APPROVED** [review]

File: src/tests/test_csv_parser.cpp [hunk 12]
```diff
@@ -0,0 +1,95 @@
...
+}
+
+TEST(TestCSVParser, TestReset) {
+    CheckReset(kACShippingDates, 6);
+    CheckReset(kadult, 32561);
+    CheckReset(kTestEmpty, 1);
+    CheckReset(kTest1, 20);
+}
+
+}  // namespace tests
```
Comment (vs9h) [inline src/tests/test_csv_parser.cpp:95]: There must be line breaks at the end of all files (we also recently added #325 a line break at the end of files for csv tables, so it’s worth adding newline in `TestParse.csv`)

File: src/tests/test_csv_parser.cpp [hunk 13]
```diff
@@ -0,0 +1,95 @@
+#include <cstddef>
```
Comment (polyntsov) [inline src/tests/test_csv_parser.cpp:1]: Try to include all standard headers which define names you're using here. These are at least `vector`, `utility`, `string`

**Review by vs9h — APPROVED** [review]

File: src/tests/test_csv_parser.cpp [hunk 14]
```diff
@@ -0,0 +1,95 @@
...
+
+namespace tests {
+
+using ::testing::ContainerEq;
+
+class TestCSVParser : public ::testing::Test {};
+
+static void CheckGetNextRow(tests::TableConfig const& table, std::size_t num_rows,
+                            std::vector<std::vector<std::string>> const& expected) {
+    auto parser = table.MakeInputTable();
```
Comment (polyntsov) [inline src/tests/test_csv_parser.cpp:17]: bad type deduction usage

File: src/tests/test_csv_parser.cpp [hunk 15]
```diff
@@ -0,0 +1,95 @@
...
+#include "all_tables_config.h"
+#include "parser/csv_parser/csv_parser.h"
+
+namespace tests {
+
+using ::testing::ContainerEq;
+
+class TestCSVParser : public ::testing::Test {};
+
+static void CheckGetNextRow(tests::TableConfig const& table, std::size_t num_rows,
```
Comment (polyntsov) [inline src/tests/test_csv_parser.cpp:15]: Why do we need `num_rows` here? It seems like `expected.size()` already has this information?

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 16]
```diff
@@ -94,6 +103,16 @@ void CSVParser::GetLine(unsigned long long const line_index) {
...
     has_next_ = !source_.eof();
+
+    /* Check for the last newline */
+    if (has_next_) {
+        source_.get();
+        if (source_.eof()) {
+            has_next_ = false;
+        }
+        source_.unget();
+    }
```
Comment (polyntsov) [inline src/core/parser/csv_parser/csv_parser.cpp:114]: A bit strange code given that right below there is an `if` with exactly the same condition, it's better to union them. Also, `get`, `eof`, `unget` sequence looks cumbersome and requires clearing of stream state in `PeekNext` which doesn't look right. Try something like this:
```cpp
    if (has_next_) {
        if (source_.peek() == std::ifstream::traits_type::eof()) {
            has_next_ = false;
            return;
        }
        GetNext();
    }
```

File: src/tests/test_csv_parser.cpp [hunk 17]
```diff
@@ -0,0 +1,95 @@
...
+#include <gtest/gtest.h>
+
+#include "all_tables_config.h"
+#include "parser/csv_parser/csv_parser.h"
+
+namespace tests {
+
+using ::testing::ContainerEq;
+
+class TestCSVParser : public ::testing::Test {};
```
Comment (polyntsov) [inline src/tests/test_csv_parser.cpp:13]: nit: anonymous namespace

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 18]
```diff
@@ -94,6 +103,16 @@ void CSVParser::GetLine(unsigned long long const line_index) {
 
 void CSVParser::GetNextIfHas() {
     has_next_ = !source_.eof();
+
+    /* Check for the last newline */
```
Comment (polyntsov) [inline src/core/parser/csv_parser/csv_parser.cpp:107]:
```suggestion
    // Check for the last newline
```
Be consistent in comment style

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 19]
```diff
@@ -77,6 +83,9 @@ void CSVParser::Reset() {
     if (has_header_) {
         SkipLine();
     }
+
+    /* For correctness of GetNextRow() after this method */
```
Comment (polyntsov) [inline src/core/parser/csv_parser/csv_parser.cpp:87]:
```suggestion
    // For correctness of GetNextRow() after this method
```

**Review by polyntsov — CHANGES_REQUESTED** [review]

File: src/core/parser/csv_parser/csv_parser.cpp [hunk 20]
```diff
@@ -59,6 +60,11 @@ void CSVParser::GetNext() {
 void CSVParser::PeekNext() {
     int len = source_.tellg();
     GetNext();
+
+    if (source_.fail()) {
+        source_.clear();
+    }
```
Comment (polyntsov) [inline src/core/parser/csv_parser/csv_parser.cpp:66]: This is not needed anymore?

**Review by polyntsov — APPROVED** [review]
